#!/bin/sh

# usage:
#
#  For gambit:
#
#    ./run --gambit --view tests/recursive/fib.scm
#    time ./tests/recursive/fib.gambit.0G4.exe
#
#  For bigloo:
#
#    ./run --bigloo --view tests/recursive/fib.scm
#    time ./tests/recursive/fib.bigloo.G.exe


SYSTEM=gambit
VIEW=no
TESTS=""

# use generic arithmetic (G) or fixnum/flonum specialized arithmetic (S)?
ARITHMETIC=G

# settings for Gambit:
VERSION_LIMIT=4
INLINING_LIMIT=0  # 0 for no function inlining

GAMBITDIR="${BBVGAMBITDIR:-../gambit}"

SCRIPT_DIR="$0"
if test "${SCRIPT_DIR#/}" = "$SCRIPT_DIR" ; then
  SCRIPT_DIR="$(pwd)/$SCRIPT_DIR"
fi
SCRIPT_DIR="${SCRIPT_DIR%/*}"
SCRIPT_DIR="${SCRIPT_DIR%/.}"

while [ "$#" != "0" ]; do
  case "$1" in
    -g|--gambit) # system
      SYSTEM=gambit
      ;;
    -b|--bigloo) # system
      SYSTEM=bigloo
      ;;
    -c|--clean) # clean
      rm -f tests/*/*.cfg tests/*/*.cfg.pdf tests/*/*.gvm tests/*/*.o* tests/*/*~ tests/*/*.bbv.dot
      exit
      ;;
    -v|--view) # view CFG
      VIEW=yes
      ;;
    -*) # other options
      printf "*** unknown option: $1\n"
      exit 1
      ;;
    *)
      TESTS="$TESTS $1"
      ;;
  esac
  shift
done

run_dot()
{
  if command -v dot > /dev/null 2>&1 ; then
    dot -O -Tpdf $1
  else
    printf "dot program not found!\n"
  fi
}

run_pdfviewer()
{
  if command -v okular > /dev/null 2>&1 ; then
    okular $1
  else
    if command -v open > /dev/null 2>&1 ; then
      open $1
    else
      printf "PDF viewer program not found!\n"
    fi
  fi
}

if test "$TESTS" = "" ; then
  TESTS="tests"
fi

FILES=""

add_file()
{
  file="$1"
  if test "${file#*.scm}" != "$file" -a "${file#*.gambit.scm}" = "$file" -a "${file#*.bigloo.scm}" = "$file" ; then
    if test "${file#/}" = "$file" ; then
      file="$(pwd)/$file"
    fi
    FILES="$FILES $file"
  fi
}

for test in $TESTS ; do
  if test -d $test ; then
    for file in $(find $test -name "*.scm") ; do
      add_file "$file"
    done
  else
    add_file "$test"
  fi
done

for file in $FILES ; do

  filenoext="${file%.scm}"

  printf "=========== $SYSTEM ${file}\n"

  case "$SYSTEM" in

    gambit)
      DECL="(declare (version-limit $VERSION_LIMIT) (inlining-limit $INLINING_LIMIT) (standard-bindings) (extended-bindings) (not safe) (block)) (define-macro (%%%) (eval '(define arithmetic '$ARITHMETIC))) (%%%)"
      base="$filenoext.gambit.$INLINING_LIMIT$ARITHMETIC$VERSION_LIMIT"
      $GAMBITDIR/gsi/gsi -:=$GAMBITDIR,drR $GAMBITDIR/gsc/igsc.scm -prelude "$DECL (##include \"$SCRIPT_DIR/gambit/bbv.scm\")" -postlude "(load \"$SCRIPT_DIR/gambit/main.scm\")" -keep-temp -gvm -cfg -exe -o $base.exe $file
      mv $filenoext.cfg $base.cfg
      run_dot $base.cfg
      CFGPDF=$base.cfg.pdf
      ANALYSISEXT=.gvm
      ;;

    bigloo)
      base="$filenoext.bigloo.$ARITHMETIC"
      (cd $SCRIPT_DIR/bigloo && \
       bigloo bbv.bgl $file -saw -fsaw-bbv -o $base.exe && \
       bglcfg $base-program.bbv.cfg > $base.dot && \
       run_dot $base-program.bbv.dot)
      CFGPDF=$base-program.bbv.dot.pdf
      ANALYSISEXT=-program.bbv.cfg
      ;;

  esac

  if test "$ANALYSISEXT" != "" && fgrep ";; $ANALYSISEXT contains: " $file > /dev/null 2>&1 ; then

    fgrep ";; $ANALYSISEXT contains: " $file | sed -e "s/^;; $ANALYSISEXT contains: //" | while IFS= read -r pattern ; do

      nboccur=$(grep -e "$pattern" $base$ANALYSISEXT | wc -l | sed -e "s/^ *//")

      case "$nboccur" in
        1) printf "SUCCESS -- $base$ANALYSISEXT contains: $pattern\n"
           ;;
        0) printf "FAIL -- pattern not found in $base$ANALYSISEXT: $pattern\n"
           ;;
        *) printf "FAIL -- pattern found $nboccur times in $base$ANALYSISEXT: $pattern\n"
           ;;
      esac

    done

  fi

  if test "$VIEW" = "yes" ; then
    run_pdfviewer $CFGPDF
  fi

done
