(define (run #!key (v (unknown '#(0 1 2 3 4))))
   (let loop ((i 0) (j (SFX- (vector-length v) 1)))
      (if (SFX< i j)
	  (let ((t (vector-ref v i)))
	     (vector-set! v i (vector-ref v j))
	     (vector-set! v j t)
	     (loop (SFX+ i 1) (SFX- j 1)))
	  v)))

(define (check result)
  (equal? result (apply vector (reverse (iota (vector-length result))))))
