#! /bin/bash

# File: "update"

# Usage: ./update

# find script directory
SCRIPT_DIR="$0"
if test "${SCRIPT_DIR#/}" = "$SCRIPT_DIR" ; then
  SCRIPT_DIR="$(pwd)/$SCRIPT_DIR"
fi
SCRIPT_DIR="${SCRIPT_DIR%/*}"
SCRIPT_DIR="${SCRIPT_DIR%/.}"

get_available_parallelism()
{
  # This works on linux:
  AVAILABLE_PARALLELISM="`nproc 2> /dev/null`"

  if [ "$AVAILABLE_PARALLELISM" == "" ] ; then

    # This works on macOS:
    AVAILABLE_PARALLELISM="`sysctl -n hw.ncpu 2> /dev/null`"

    if [ "$AVAILABLE_PARALLELISM" == "" ] ; then
      # Just assume we have one processing unit
      AVAILABLE_PARALLELISM="1"
    fi

  fi
}

get_available_parallelism

MAKE_JOBS="-j$AVAILABLE_PARALLELISM"

BIGLOOREPODIR="$SCRIPT_DIR/bigloo"
BIGLOOINSTDIR="$SCRIPT_DIR/local"
BIGLOOGIT=https://github.com/manuel-serrano/bigloo.git

# when BIGLOOURL is defined it will override getting bigloo from the git repo
BIGLOOURL=http://www-sop.inria.fr/indes/fp/Bigloo/download/bigloo-unstable.tar.gz

if [ ! -z "$BIGLOOURL" -o ! -d "$BIGLOOREPODIR" ] ; then

  if [ -n "$BIGLOOURL" ] ; then

    echo "========== downloading Bigloo to $BIGLOOREPODIR from $BIGLOOURL"

    rm -rf bigloo-unstable.tar.gz bigloo-unstable "$BIGLOOREPODIR" "$BIGLOOINSTDIR"
    curl "$BIGLOOURL" > bigloo-unstable.tar.gz
    tar zxf bigloo-unstable.tar.gz
    mv bigloo-unstable bigloo

  else

    echo "========== cloning Bigloo to $BIGLOOREPODIR"

    git clone $BIGLOOGIT "$BIGLOOREPODIR"

  fi

  cd "$BIGLOOREPODIR"

  echo "========== configuring Bigloo"

  if [ `uname -s` = "Darwin" ] ; then
    GCC=gcc-13
  else
    GCC=gcc
  fi

  CC=$GCC ./configure --prefix="$BIGLOOINSTDIR" --disable-unistring

  echo "========== building Bigloo"

  make "$MAKE_JOBS" || exit 1
  
  echo "========== installing Bigloo"

  make install || exit 1

  echo "========== installing bglcfg"

  make -C tools bglcfg

else

  cd "$BIGLOOREPODIR"

  git pull > pull.out

  cat pull.out

  if grep -q -v 'Already up-to-date.' pull.out > /dev/null ; then

    echo "========== reconfiguring Bigloo"

    ./configure --prefix="$BIGLOOINSTDIR"

    echo "========== building Bigloo with recent changes"

    make "$MAKE_JOBS" || exit 2

    echo "========== installing Bigloo"

    make install || exit 2

  fi

  rm -f pull.out
fi  

echo "========== Bigloo is up to date"
