(let loop1 ((args (map (lambda (arg) (call-with-input-string arg read))
                       (cdr (command-line))))
            (rev-args '())
            (repeat 1))
  (if (and (pair? args) (pair? (cdr args)))
      (let ((arg (car args)))
        (if (eq? arg 'repeat:)
            (loop1 (cddr args) rev-args (cadr args))
            (loop1 (cddr args) (cons (cadr args) (cons (car args) rev-args)) repeat)))
      (if (pair? args)
          (error "invalid arguments")
          (let ((args (reverse args)))
            (let loop2 ((repeat repeat))
              (if (> repeat 0)
                  (begin
                    (apply run args)
                    (loop2 (- repeat 1)))))))))
